// Generate sitemap.xml from books.json + blog posts + static pages.
// Run after adding a book or blog post: node scripts/build-sitemap.js
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const SITE = 'https://certpathpublishing.store';
const ROOT = path.join(__dirname, '..');
const today = new Date().toISOString().slice(0, 10);

// lastmod comes from the file's last commit date, not the build date. Stamping
// every URL with today on each run tells Google all 78 pages changed daily,
// which makes it discount the signal for the whole site.
function lastmodOf(file) {
  if (!file) return today;
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return out || today;
  } catch {
    return today;
  }
}

const urls = [
  { loc: `${SITE}/`, priority: '1.0', changefreq: 'weekly', file: 'index.html' },
  { loc: `${SITE}/access`, priority: '0.9', changefreq: 'monthly', file: 'access.html' },
  { loc: `${SITE}/blog/`, priority: '0.7', changefreq: 'daily', file: 'blog/posts.json' },
];

// Per-exam landing pages (generated by build-exam-pages.js) plus the hand-built
// ones. Anything indexable belongs here; /sample, /my and /quiz are deliberately
// left out because they are noindex or gated app pages, not landing pages.
for (const p of ['sat', 'ged', 'tabe', 'ccrn', 'cast', 'mechanical-aptitude', 'journeyman-electrician', 'poss', 'csp', 'chst', 'psat', 'act',
                 'pmp', 'capm', 'cnor', 'pmp-readiness']) {
  if (fs.existsSync(path.join(ROOT, `${p}.html`))) {
    urls.push({ loc: `${SITE}/${p}`, priority: '0.9', changefreq: 'weekly', file: `${p}.html` });
  }
}

urls.push({ loc: `${SITE}/exams`, priority: '0.9', changefreq: 'weekly', file: 'exams.html' });
for (const p of ['privacy', 'terms', 'refunds']) {
  urls.push({ loc: `${SITE}/${p}`, priority: '0.2', changefreq: 'yearly', file: `${p}.html` });
}

// Dedicated book pages (generated by build-book-pages.py)
for (const f of fs.existsSync(path.join(ROOT, 'books')) ? fs.readdirSync(path.join(ROOT, 'books')) : []) {
  if (f.endsWith('.html')) urls.push({ loc: `${SITE}/books/${f.replace('.html', '')}`, priority: '0.8', changefreq: 'monthly', file: `books/${f}` });
}

// Per-book ebook landing pages (published books that actually sell a PDF edition)
const books = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/books.json'), 'utf8')).books;
for (const b of books.filter(x => x.published && x.payhipEbookUrl)) {
  urls.push({ loc: `${SITE}/ebook?book=${b.slug}`, priority: '0.8', changefreq: 'monthly', file: 'ebook.html' });
}

// Blog posts
for (const f of fs.readdirSync(path.join(ROOT, 'blog'))) {
  if (f.endsWith('.html') && f !== 'index.html') {
    urls.push({ loc: `${SITE}/blog/${f.replace('.html', '')}`, priority: '0.6', changefreq: 'yearly', file: `blog/${f}` });
  }
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...urls.map(u => `  <url><loc>${u.loc}</loc><lastmod>${lastmodOf(u.file)}</lastmod><changefreq>${u.changefreq}</changefreq><priority>${u.priority}</priority></url>`),
  '</urlset>',
  '',
].join('\n');

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);
console.log(`sitemap.xml written: ${urls.length} URLs`);
